### PR TITLE
Get delete working

### PR DESCRIPTION
**Pull request by benjaminwood**
Sup Oscar 😄 

The application layout wasn't rendering your view content because `yield` was indented under the flash message iteration. 

The delete link wasn't working because your application.js wasn't being loaded due to `javascript_include_tag` vs `javascript_pack_tag`. Justin Bowen was on the right track identifying the problem being that nothing was handling `method: :delete`.

### CODE REVIEW

**Comment by creaturenex** [comment]
Hows it going Ben!

I actually found an overstack comments regarding `stylesheet /javascript_pack_tag` and tried it, but didn't work but I think it also had to do with the missing `require jquery / jquery_ujs / tree`, totally missed the `yield` indention. Justin's article was very informative :). Not sure how I missed that.

**Comment by TonsOfFun** [comment]
Nice @benjaminwood! I found haml’s format always gave me more trouble than it’s worth.

**Comment by creaturenex** [comment]
What are your recommendations besides haml? or do you typically just use erb?

**Comment by TonsOfFun** [comment]
I usually just use erb.

**Comment by creaturenex** [comment]
@TonsOfFun, @benjaminwood

Thanks for the help! I decided to start over in ERB and got a working demo! Managed to deploy to Heroku used active storage, devise, bootstrap, and aws s3 for bucket storage. I have some minor items to address but thank you for your help. I would appreciate any feedback. @TonsOfFun the rails db:reset did the trick for me clearing the issues I had with migrating a previous db instance.

http://pin-clone-020722.herokuapp.com/
https://github.com/creaturenex/return_of_the_pinclone/

**Pull request merged**
